#!/bin/bash
LOG_FILE="/var/log/auth.log"
THRESHOLD=10000

echo "Mendeteksi serangan SSH..."
awk '/Failed password/ {print $(NF-3)}' $LOG_FILE | sort | uniq -c | while read attempts ip; do
  if [ "$attempts" -gt "$THRESHOLD" ]; then
    echo "Memblokir IP: $ip"10.84.91.231"
    sudo iptables -A INPUT -s $ip -j DROP
  fi
done
