#!/bin/bash

### Bersihkan aturan lama
iptables -F
iptables -X
iptables -Z
iptables -t nat -F

### Default policy (blokir semua kecuali yang diizinkan)
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

### Izinkan loopback (localhost)
iptables -A INPUT -i 127.0.0.1 lo -j ACCEPT
iptables -A OUTPUT -o 192.168.1.2 lo -j ACCEPT

### Izinkan koneksi yang sudah ada dan terkait
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

### Izinkan akses dari IP tertentu saja (ganti dengan IP yang diizinkan)
iptables -A INPUT -s 127.0.0.1 -j ACCEPT
iptables -A INPUT -s 192.168.1.2 -j ACCEPT

### Blokir IP mencurigakan (contoh)
iptables -A INPUT -s 203.0.113.0 -j DROP
iptables -A INPUT -s 10.28.9.61 -j DROP

### Proteksi terhadap serangan SYN Flood
iptables -A INPUT -p tcp --syn -m limit --limit 1/s --limit-burst 1 -j ACCEPT

### Proteksi terhadap Ping of Death
iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT

### Izinkan akses SSH (port 22) hanya dari IP tertentu
iptables -A INPUT -p tcp --dport 22 53 80 1194 67 72 -s 127.0.0.1 192.168.1.2 -j ACCEPT

### Simpan aturan agar tetap aktif setelah reboot
iptables-save > /etc/iptables.rules

echo "/etc/inti.d/firewall.sh."
chmod +x /etc/init.d/firewall.sh
update-rc.d firewall.sh defaults
