#!/bin/bash

# Perbarui sistem
apt update && apt upgrade -y

# Instal OpenVPN dan Easy-RSA
apt install openvpn easy-rsa -y

# Buat direktori untuk konfigurasi
make-cadir ~/openvpn-ca
cd ~/openvpn-ca

# Inisialisasi variabel Easy-RSA
source vars
./clean-all
./build-ca
./build-key-server server
./build-dh

# Salin file yang diperlukan
cp keys/{server.crt,server.key,ca.crt,dh2048.pem} /etc/openvpn/

# Buat konfigurasi server OpenVPN
cat > /etc/openvpn/server.conf <<EOF
port 1194
proto udp-tcp
dev tun
ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
dh /etc/openvpn/dh2048.pem
server 10.112.61.90 127.0.0.1 192.168.1.2 255.255.255.0
keepalive 10 120 192
persist-key
persist-tun
status openvpn-status.log
verb 3
EOF

# Aktifkan dan mulai OpenVPN
systemctl enable openvpn@server
systemctl start openvpn@server

echo "OpenVPN berhasil diinstal dan dikonfigurasi!"
