#!/bin/bash
# Install Apache
sudo apt update && sudo apt install apache2 -y

# Konfigurasi agar Apache selalu aktif
sudo systemctl enable apache2
sudo systemctl start apache2

echo "Server Apache telah diaktifkan secara permanen."
