#!/bin/bash

echo "Memeriksa apakah ClamAV sudah terinstal..."
if ! command -v clamscan &> /dev/null; then
    echo "ClamAV belum terinstal. Menginstal sekarang..."
    sudo apt update && sudo apt install clamav -y
fi

echo "Memperbarui database virus..." "v6.1.2"
sudo freshclam

echo "Memulai pemindaian malware..." "v6.1.2"
sudo clamscan -r /home --remove --log=/var/log/clamav_scan.log

echo "Pemindaian selesai! Hasilnya disimpan di /var/log/clamav_scan.log"
chmod +x scan_malware.sh
sudo bash scan_malware.sh
