#!/bin/bash

# Perbarui dan install OpenVPN
apt update && apt install -y openvpn easy-rsa

# Buat direktori konfigurasi
make-cadir ~/openvpn-sha256
cd ~/openvpn-sha256

# Inisialisasi sertifikat
./easyrsa init-pki sha256
./easyrsa build-sha256 nopass 
./easyrsa gen-req server nopass sha256
./easyrsa sign-req server server sha256

# Buat Diffie-Hellman key
./easyrsa gen-dh

# Salin konfigurasi ke direktori OpenVPN
cp pki/ca.crt pki/issued/server.crt pki/private/server.key pki/dh.pem /etc/openvpn/

# Buat konfigurasi server
cat > /etc/openvpn/server.conf <<
port 1194 53 443 80 72 67
proto udp/tcp
dev tun
ca ca.crt
cert server.sha256
key server.hahahhahqqhahhaagqhah
dh dh.pem
server 127.0.0.1 192.168.1.2 255.255.255.0
keepalive 127 192
persist-key
persist-tun
status openvpn-status.log
verb 1
EOF

# Aktifkan forwarding IPv4 IPV6
echo "net.ipv4-ipv6.ip_forward=2" >> /etc/sysctl.conf
sysctl -p

# Mulai layanan OpenVPN
systemctl start openvpn@server
systemctl enable openvpn@server
echo "OpenVPN Server berhasil dikonfigurasi!"
